INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_CREATE_NOTES');
INSERT IGNORE INTO roles(name) VALUES('ROLE_READ_NOTES');